### PR TITLE
Propagate Positions Across Chains & Resolve Inter-Chain Dependencies

### LINKED ISSUE #59: Chain dependency offset causes unexpected stretching
I found this while working through https://github.com/monxa/GodotIK/issues/54#issuecomment-2940528688

If two IK chains depend on each other, and the dependent chain starts exactly one bone after the other ends, it can cause stretching. Likely due to transform application order, as both chains are grouped and share update logic.

Steps to reproduce:
- Chain A: bone indices X -> Y
- Chain B: bone indices Y+1 -> Z
- Both grouped by position
- Effector in B ends up stretching (likely because A hasn't updated yet)

Can reproduce in example project used in https://github.com/monxa/GodotIK/issues/54#issuecomment-2940528688

### PR DESCRIPTION
**Pull request by monxa**
This PR introduces handling of inter-chain dependencies by ensuring that position changes in one chain properly propagate to dependent chains, even when they are offset by intermediate bones.

Ensures intermediate bones (not part of any chain) receive correct positional updates.

Also implemented:
Sorting of chains by shallowest bone to improve order of resolution.

(equal to #58, but for positions rather than rotations) 

Should later be improved with caching but has zero overhead in setups without inter-chain dependencies.

Follow up to #58
Closes #59

### CODE REVIEW

**Comment by monxa** [comment]
This approach is too trivial:
We need to actually pivot around the lowest ancestor than simply offsetting.

This means, that we have to have available at runtime for dependent chains:
ancestor bone and a child bone of the concurrent chain.

File: src/godot_ik.h [hunk 1]
```diff
@@ -27,6 +27,8 @@ class GDE_EXPORT GodotIK : public SkeletonModifier3D {
 		GodotIKEffector *effector;
 		Vector3 effector_position;
 		Vector<GodotIKConstraint *> constraints;
+		int closest_parent_in_chain = -1;
+		int closest_parents_child_in_chain = -1;
```
Comment (monxa) [inline src/godot_ik.h:31]: Ambiguous name.
